name: Pryv service-core CI

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
     
jobs:
  build:

    runs-on: macOS-latest
    
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 11,OS=10.0']

    steps:
    - name: Download master branch
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        pod install --repo-update
      shell: bash
        
    - name: Build and test
      run: |
        xcodebuild clean test -project PryvSwiftKit.xcodeproj -scheme Texstyle -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        bash <(curl -s https://codecov.io/bash)
      env:
       destination: ${{ matrix.destination }}
