name: Pryv lib swift

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
     
jobs:
  test:

    runs-on: macOS-latest
    
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 11,OS=10.0']
        xcode: ['/Applications/Xcode_11.1.app/Contents/Developer']

    steps:
    - name: Download master branch
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        pod install
      shell: bash
      env:
        DEVELOPER_DIR: ${{ matrix.xcode }}
        
    - name: Build and test
      run: |
        xcodebuild clean test -project PryvSwiftKit.xcodeproj -scheme Texstyle -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        bash <(curl -s https://codecov.io/bash)
      env:
       destination: ${{ matrix.destination }}
